---
- hosts: all

  vars_files:
    - default.config.yml

  # if you need to repeatedly run install and this prompt is annoying, comment this section out and the following to
  # config.yml:
  #
  #   mas_email: <email>
  #   mas_password: <password>
  vars_prompt:
    - name: mas_email
      prompt: Enter Mac App Store email address
      private: no
    - name: mas_password
      prompt: Enter Mac App Store password

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']
    - role: gantsign.oh-my-zsh
      when: configure_oh_my_zsh
      users: "{{ oh_my_zsh_users }}"
      tags: ['oh-my-zsh']

  tasks:
    - import_tasks: tasks/macos.yml
      when: configure_macos
      tags: ['macos']
    - import_tasks: tasks/post-ohmyzsh.yml
      when: configure_oh_my_zsh
      tags: ['oh-my-zsh']
    - import_tasks: tasks/krew.yml
      when: configure_krew
      tags: ['krew']
    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']
    - import_tasks: tasks/iterm2.yml
      tags: ['iterm2']
      when: configure_iterm2
    - import_tasks: tasks/nvm.yml
      tags: ['nvm']
      when: configure_nvm
    - import_tasks: tasks/tmux-config.yml
      tags: ['tmux-config']
      when: configure_tmux
    - import_tasks: tasks/vim.yml
      tags: ['vim']
      when: configure_vim
    - import_tasks: tasks/debug.yml

    - block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']
